spring:
  application:
    name: mos-core-lib
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000


springdoc:
  title: "MOS Core API"
  description: "Core library providing common services and utilities"
  version: "1.0.0"
  contact:
    name: "MOS Dev Team"
    email: "support@mos.vn"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"


logging:
  level:
    org.springframework.security: DEBUG
    vn.mos.core: DEBUG

jwt:
  secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz
  expiration: 3600000