spring:
  application:
    name: mos-core-lib
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true

feign:
  client:
    config:
      default:
        connect-timeout: 3000
        read-timeout: 3000

jwt:
  secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz
  expiration: 3600000