spring:
  application:
    name: mos-core-lib
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: none
    show-sql: true
  data:
    redis:
      prefix: app
      host: redis-14343.c1.ap-southeast-1-1.ec2.redns.redis-cloud.com
      port: 14343
      username: default
      password:
      timeout: 30000

feign:
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000

rest-template:
  client:
    config:
      default:
        connect-timeout: 30000
        read-timeout: 30000

springdoc:
  title: "MOS Core API"
  description: "Core library providing common services and utilities"
  version: "1.0.0"
  contact:
    name: "MOS Dev Team"
    email: "support@mos.vn"
  license:
    name: "MIT"
    url: "https://opensource.org/licenses/MIT"

security:
  public-routes:
    - "/v1/public/**"
    - "/swagger-ui/**"
    - "/v3/api-docs/**"

logging:
  level:
    org.springframework.security: DEBUG
    vn.mos.core: DEBUG

jwt:
  secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789abcdefghijklmnopqrstuvwxyz
  expiration: 3600000